#define WORDS_PER_FRAME 93
#define FRAMES_PER_BRAM 256
#define DATA_DMA_OFFSET 0x1FCU

// bitstream ctrl commands
#define WORDS_BETWEEN_FRAMES 7
#define WORDS_AFTER_FRAMES 54
#define WORDS_BEFORE_FRAMES 196

